# CloudFormation GitSync Deployment Configuration
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/git-sync-concepts-terms.html

template-file-path: ./fault-tolerant-web-app.yaml

stack-name: fault-tolerant-web-stack

region: eu-central-1

parameters:
  LatestAmiId: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  VpcId: vpc-xxxxxxxx
  PublicSubnetIds: subnet-aaaaaaaa,subnet-bbbbbbbb
  KeyPairName: my-key-pair

tags:
  Project: fault-tolerant-web-stack
  Environment: demo
  ManagedBy: CloudFormation-GitSync